### ISSUE TITLE
Szulok menupont tervezese megvalosítasa 

### ISSUE THREAD

**Issue by lazarferenc** [lazarferenc/ProjectX#2]
Szulok menupont prototipusanak megvalosítasa es annak dokumentalasa 2016.10.21-ig Lazar Ferenc

**Comment by lazarferenc** [comment]
A feldatatot elkezdtem elore lathatolag holnap kora delutani orakban veglegesitem.

**Comment by d3ad93** [comment]
Update

**Comment by d3ad93** [comment]
completed
